#!/usr/bin/python3
"""
    Route for state objects
"""
from models.state import State
from models import storage
from flask import abort, jsonify
from api.v1.views import app_views


@app_views.route("/states")
@app_views.route("/states/<state_id>")
def retrieve_states(state_id=None):
    """Return all state object"""
    objs = storage.all().values()
    if state_id:
        objList = [obj for obj in objs if state_id == obj.id]
        return jsonify(objList[0].to_dict())
        abort(404)
    else:
        objList = [obj.to_dict() for obj in objs]
        return jsonify(objList)

@app_views.route("/api/v1/states/<state_id>", methods=['DELETE'])
def delete_state(state_id=None):
    """Removes a state"""
    states = storage.all().values()
    objList = [obj for obj in objs if state_id == obj.id]
    if objList:
        storage.delete(objList[0])
        storage.save()
        return jsonify({})

    abort(404)

